version: 2.1
orbs:
  perl: circleci/perl@1.0.0
workflows:
  main:
    jobs:
      - perl/build:
          save-to-workspace: true
      - perl/test-linux:
          perl-version: "5.10"
          requires: ["perl/build"]
